In [1]:
# colectii: liste, tuple, range, string, dictionar

In [ ]:
#         0    1     2     3    4
o_lista = [23, 121, 200, 300, 404]
len(o_lista)

5

In [4]:
o_lista[4]


404

In [5]:
o_lista[len(o_lista) - 1]

404

In [6]:
o_lista[ - 1]

404

In [8]:
o_lista = [23, 121, 200, 300, 404]
o_lista[0:2]

[23, 121]

In [9]:
o_lista = [23, 121, 200, 300, 404]
o_lista[-2:-1]

[300]

In [10]:
o_lista = [23, 121, 200, 300, 404]
o_lista[-2:]

[300, 404]

In [11]:
o_lista = [23, 121, 200, 300, 404]
o_lista[:2]

[23, 121]

In [12]:
o_lista = [23, 121, 200, 300, 404]
o_lista[:]

[23, 121, 200, 300, 404]

In [13]:
o_lista = [23, 121, 200, 300, 404]
o_lista[:5:2]

[23, 200, 404]

In [14]:
o_lista = [23, 121, 200, 300, 404]
o_lista[::-1]

[404, 300, 200, 121, 23]

In [15]:
text = "buna ziua"
text [0]

'b'

In [16]:
text [-1]

'a'

In [ ]:
text [-4:]

'ziua'

In [18]:
text [:4]

'buna'

In [19]:
text = "buna ziua"
text[::-1]

'auiz anub'

In [20]:
text = "buna ziua"
text.split()

['buna', 'ziua']

In [21]:
text = "buna ziua"
text.split()[::-1]

['ziua', 'buna']

In [23]:
text = "buna ziua"
" ".join(text.split()[::-1])

'ziua buna'

In [24]:
text = "buna ziua"
"_".join(text.split()[::-1])

'ziua_buna'

In [25]:
text = "buna ziua oameni frumosi"
"_".join(text.split()[::-1])

'frumosi_oameni_ziua_buna'

# slice in numpy

In [26]:
import numpy as np

In [28]:
arr = np.random.randint(1, 100, 10)
arr

array([83, 53, 11, 61, 51, 64, 89, 73, 13, 14])

In [29]:
arr[2:6]

array([11, 61, 51, 64])

In [30]:
arr = np.random.randint(1, 100, (3, 2))
arr

array([[57,  4],
       [66, 10],
       [ 2, 59]])

In [31]:
arr[1]

array([66, 10])

In [32]:
arr[1][0]

np.int64(66)

In [33]:
arr[1, 0]

np.int64(66)

In [34]:
arr = np.random.randint(1, 100, (3, 2))
arr

array([[31, 79],
       [19, 51],
       [93, 25]])

In [35]:
arr[ : , 0 ]

array([31, 19, 93])

In [36]:
arr[ : , 1 ]

array([79, 51, 25])