In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# mp, suprafata
apartamente = np.array([
    (40, 65_000), (49, 71_000), (50, 75_000), (57, 83_000), (60, 120_000), (73, 154_000), (85, 170_000), (91, 210_000), (100, 300_000)
])

In [3]:
suprafete = apartamente[:, 0]
preturi = apartamente[:, 1]

In [5]:
plt.scatter(suprafete, preturi, c="red")
plt.plot(suprafete, preturi);

In [6]:
from sklearn.linear_model import LinearRegression

In [8]:
model = LinearRegression()
model

LinearRegression()

In [10]:
suprafete

array([ 40,  49,  50,  57,  60,  73,  85,  91, 100])

In [12]:
suprafete_2d = suprafete.reshape(-1, 1)
suprafete_2d

array([[ 40],
       [ 49],
       [ 50],
       [ 57],
       [ 60],
       [ 73],
       [ 85],
       [ 91],
       [100]])

In [13]:
model.fit(suprafete_2d, preturi)

LinearRegression()

In [15]:
model.coef_, model.intercept_

(array([3603.60303413]), np.float64(-103575.53729456392))

In [17]:
# comparam cu valorile din scipy
slope=np.float64(3603.603034134008)
intercept=np.float64(-103575.5372945639)

In [18]:
plt.scatter(suprafete, preturi , c="red")
plt.plot(suprafete, model.coef_ * suprafete + model.intercept_, c="black");

In [19]:
model

LinearRegression()

In [20]:
print("Pretul unui apartament cu 68 mp este:", model.predict([      [68],        ]))

Pretul unui apartament cu 68 mp este: [141469.46902655]


In [21]:
print("Pretul unui apartament cu 45 mp este:",  model.predict([ [45]]))

Pretul unui apartament cu 45 mp este: [58586.59924147]
