# pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Omogenitate -> acelasi tip de date

In [3]:
np.array([1, 2, 3, 5, 5, 32])

array([ 1,  2,  3,  5,  5, 32])

In [4]:
arr = np.array([1, 2, 3, 5, 5, 32])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [5]:
arr = np.array([1, 2, 3, 5.32, 5.321, 32])
arr, arr.dtype

(array([ 1.   ,  2.   ,  3.   ,  5.32 ,  5.321, 32.   ]), dtype('float64'))

In [6]:
arr = np.array([1, 2, 3, 5.32, 5.321, 32, "hello"])
arr, arr.dtype

(array(['1', '2', '3', '5.32', '5.321', '32', 'hello'], dtype='<U32'),
 dtype('<U32'))

# Omogenitate -> acelasi shape

In [7]:
arr = np.array([1, 2, 3, 5.32, 5.321, 32, "hello", [32, 32, 100]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

In [8]:
arr = np.array([1, 2, 3, 5.32, 5.321, 32, "hello"])
arr.shape

(7,)

In [9]:
arr = np.array([[1, 2, 3], [5.32, 5.321, "hello"], [32, 32, 100]])
arr.shape, arr

((3, 3),
 array([['1', '2', '3'],
        ['5.32', '5.321', 'hello'],
        ['32', '32', '100']], dtype='<U32'))

In [10]:
arr = np.array([[1, 2, 3],  [32, 32, 100]])
arr.shape, arr

((2, 3),
 array([[  1,   2,   3],
        [ 32,  32, 100]]))

# Numpy functioneaza cu range sau random

In [11]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(4, 12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(4, 12, 3)

array([ 4,  7, 10])

In [15]:
np.arange(4, 12, 3, dtype=np.float64)

array([ 4.,  7., 10.])

In [16]:
np.random.randint(1, 10)

4

In [17]:
np.random.randint(1, 10, 4)

array([3, 7, 4, 1])

In [18]:
np.random.randint(1, 10, (2, 3))

array([[8, 5, 8],
       [5, 6, 3]])

In [19]:
np.random.randint(low=1, high=10, size=(2, 3))

array([[8, 7, 4],
       [2, 3, 7]])

# Data type

In [21]:
arr = np.random.randint(1, 10, 4)
arr, arr.dtype

(array([6, 7, 1, 9]), dtype('int64'))

In [22]:
bin(10)

'0b1010'

In [27]:
for i in range(2 ** 8):
    print("i = ", i, "bin = ", bin(i)[2:])

i =  0 bin =  0
i =  1 bin =  1
i =  2 bin =  10
i =  3 bin =  11
i =  4 bin =  100
i =  5 bin =  101
i =  6 bin =  110
i =  7 bin =  111
i =  8 bin =  1000
i =  9 bin =  1001
i =  10 bin =  1010
i =  11 bin =  1011
i =  12 bin =  1100
i =  13 bin =  1101
i =  14 bin =  1110
i =  15 bin =  1111
i =  16 bin =  10000
i =  17 bin =  10001
i =  18 bin =  10010
i =  19 bin =  10011
i =  20 bin =  10100
i =  21 bin =  10101
i =  22 bin =  10110
i =  23 bin =  10111
i =  24 bin =  11000
i =  25 bin =  11001
i =  26 bin =  11010
i =  27 bin =  11011
i =  28 bin =  11100
i =  29 bin =  11101
i =  30 bin =  11110
i =  31 bin =  11111
i =  32 bin =  100000
i =  33 bin =  100001
i =  34 bin =  100010
i =  35 bin =  100011
i =  36 bin =  100100
i =  37 bin =  100101
i =  38 bin =  100110
i =  39 bin =  100111
i =  40 bin =  101000
i =  41 bin =  101001
i =  42 bin =  101010
i =  43 bin =  101011
i =  44 bin =  101100
i =  45 bin =  101101
i =  46 bin =  101110
i =  47 bin =  101111
i =  48 bin =  1

# UINT 8 - > de la 0 la 255 (2 ** 8 - 1)

In [29]:
arr = np.array([1, 255, 100], dtype=np.uint8)
arr

array([  1, 255, 100], dtype=uint8)

In [30]:
arr = np.array([1, 256, 100], dtype=np.uint8)
arr

OverflowError: Python integer 256 out of bounds for uint8

# INT 8 - > de la -128 (-2 ** 7) la 127 (2 ** 7 - 1)

In [31]:
arr = np.array([1, -128, 127], dtype=np.int8)
arr

array([   1, -128,  127], dtype=int8)

In [32]:
arr = np.array([1, -129, 127], dtype=np.int8)
arr

OverflowError: Python integer -129 out of bounds for int8

In [33]:
arr = np.array([1, -128, 128], dtype=np.int8)
arr

OverflowError: Python integer 128 out of bounds for int8

# Fast mathematical operations over arrays

# 1. Map (operatii matematice si logice)

In [34]:
arr = np.array([10, 20, 15, 30, 9, 8])
arr

array([10, 20, 15, 30,  9,  8])

In [35]:
arr * 2

array([20, 40, 30, 60, 18, 16])

In [36]:
arr + 10

array([20, 30, 25, 40, 19, 18])

In [38]:
arr1 = np.array([10, 20, 15, 30, 9, 8])
arr2 = np.array([12, 10,  5, 10, 4, 1])

arr1 - arr2

array([-2, 10, 10, 20,  5,  7])

In [40]:
arr1 = np.array([10, 20, 15, 30, 9, 8])
arr2 = np.array([12, 10,  5, 10, 4])

arr1 - arr2 # aici lungimile sunt egale

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [41]:
arr = np.array([10, 20, 15, 30, 9, 8])
arr > 10

array([False,  True,  True,  True, False, False])

# 2. Filter

In [42]:
arr = np.array([10, 20, 15, 30, 9, 8])
arr[arr > 10]

array([20, 15, 30])

In [43]:
arr = np.array([10, 20, 15, 30, 9, 8])

conditie = arr > 10

arr[conditie]

array([20, 15, 30])

In [44]:
arr = np.array([10, 20, 15, 30, 9, 8])

conditie1 = arr > 11
conditie2 = arr < 29

arr[conditie1 & conditie2]

array([20, 15])

In [48]:
# Operatii logice
print("True and True = ", True and True)
print("False and True = ", False and True)

print("True or True = ", True or True)
print("False or True = ", False or True)

print( "not True = ", not True)
print("not False = ", not False)


True and True =  True
False and True =  False
True or True =  True
False or True =  True
not True =  False
not False =  True


# 3. Reduce

In [49]:
o_lista = [23, 32, 15, 51, 20, 30]
sum(o_lista), min(o_lista), max(o_lista), len(o_lista)

(171, 15, 51, 6)

In [50]:
un_arr = np.array([23, 32, 15, 51, 20, 30])
sum(un_arr), min(un_arr), max(un_arr), len(un_arr)

(np.int64(171), np.int64(15), np.int64(51), 6)

In [52]:
un_arr = np.array([23, 32, 15, 51, 20, 30])
un_arr.sum(), un_arr.min(), un_arr.max(), un_arr.size, un_arr.shape

(np.int64(171), np.int64(15), np.int64(51), 6, (6,))

In [53]:
un_arr = np.array([[23, 32, 15], [51, 20, 30]])
print("size=", un_arr.size)
print("shape=", un_arr.shape)

size= 6
shape= (2, 3)


In [54]:
un_arr = np.array([23, 32, 15, 51, 20, 30])
un_arr.mean(), un_arr.sum()/un_arr.size

(np.float64(28.5), np.float64(28.5))

In [55]:
un_arr = np.array([23, 32, 15, 51, 20, 30])
un_arr.min(), un_arr.argmin()

(np.int64(15), np.int64(2))